httpsListner:
  protocol: "HTTPS"
  host: "0.0.0.0" 
  port: "8082"
  trust-store-password: "mulesoft"
  key-store-keyPassword: "mulesoft"
  key-store-password: "mulesoft"
  
httpsRequest:
  protocol: "HTTPS"  
  host: "localhost"
  port: "8082"
  trust-store-password: "mulesoft"
  key-store-keyPassword: "mulesoft"
  key-store-password: "mulesoft"